SELECT
    COUNT(DISTINCT(PASSO.ID)) AS PASSO_COUNT,
    CASE WHEN COUNT(DISTINCT PASSO.ID) = 15 THEN TRUE ELSE FALSE END AS IS_COMPLETE
FROM PESSOA
    INNER JOIN MATRICULA
        ON PESSOA.ID = MATRICULA.ALUNO_ID

    LEFT JOIN ALUNO
        ON PESSOA.ID = ALUNO.ID

    INNER JOIN SESSAOEXEC
        ON MATRICULA.ID = SESSAOEXEC.MATRICULA_ID

    INNER JOIN PASSOEXEC
        ON SESSAOEXEC.ID = PASSOEXEC.SESSAOEXEC_ID

    INNER JOIN PASSOOCORRENCIA AS PASSO_OCOR
        ON PASSOEXEC.OCORRENCIA_ID = PASSO_OCOR.ID

    LEFT JOIN PASSO
        ON PASSO.ID = PASSO_OCOR.PASSO_ID

WHERE
    SESSAOEXEC.CANCELADA = 0
    AND MATRICULA.PROJETO_ID = 132
    AND MATRICULA.PROGRAMA_ID = :PROGRAM_ID
    AND PASSO.ID in (1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002)
    AND MATRICULA.ALUNO_ID = :STUDENT_ID;