SELECT
    COUNT(DISTINCT(PASSO.ID)) AS PASSO_COUNT,
    CASE WHEN COUNT(DISTINCT PASSO.ID) = 20 THEN TRUE ELSE FALSE END AS IS_COMPLETE
FROM PESSOA
    INNER JOIN MATRICULA
        ON PESSOA.ID = MATRICULA.ALUNO_ID

    LEFT JOIN ALUNO
        ON PESSOA.ID = ALUNO.ID

    INNER JOIN SESSAOEXEC
        ON MATRICULA.ID = SESSAOEXEC.MATRICULA_ID

    INNER JOIN PASSOEXEC
        ON SESSAOEXEC.ID = PASSOEXEC.SESSAOEXEC_ID

    INNER JOIN PASSOOCORRENCIA AS PASSO_OCOR
        ON PASSOEXEC.OCORRENCIA_ID = PASSO_OCOR.ID

    LEFT JOIN PASSO
        ON PASSO.ID = PASSO_OCOR.PASSO_ID

WHERE
    SESSAOEXEC.CANCELADA = 0
    AND MATRICULA.ID = :REGISTRATION_ID
    AND MATRICULA.PROJETO_ID = 132
    AND MATRICULA.PROGRAMA_ID = :PROGRAM_ID
    AND PASSO.ID in (375,395,412,419,425,400,413,431,437,312,319,324,499,327,352,358,364,511,549,552)
    AND MATRICULA.ALUNO_ID = :STUDENT_ID;