SELECT
	PESSOA.ID,
    PESSOA.NOMECOMPLETO AS FULLNAME,
    PESSOA.DATANASCIMENTO AS BIRTHDATE,
    PESSOA.SEXO AS SEX

FROM PESSOA
WHERE PESSOA.ID IN (
    SELECT MATRICULA.ALUNO_ID
    FROM MATRICULA
    WHERE MATRICULA.PROJETO_ID = 132
)