SELECT
    COUNT(DISTINCT(BLOCO.ID)) AS BLOCK_COUNT,
    CASE WHEN COUNT(DISTINCT BLOCO.ID) = 6 THEN TRUE ELSE FALSE END AS IS_COMPLETE
FROM PESSOA
    INNER JOIN MATRICULA
        ON PESSOA.ID = MATRICULA.ALUNO_ID
    LEFT JOIN ALUNO
        ON PESSOA.ID = ALUNO.ID
    INNER JOIN SESSAOEXEC
        ON MATRICULA.ID = SESSAOEXEC.MATRICULA_ID
    INNER JOIN PASSOEXEC
        ON SESSAOEXEC.ID = PASSOEXEC.SESSAOEXEC_ID
    INNER JOIN PASSOOCORRENCIA AS PASSO_OCOR
        ON PASSOEXEC.OCORRENCIA_ID = PASSO_OCOR.ID
    LEFT JOIN PASSO
        ON PASSO.ID = PASSO_OCOR.PASSO_ID
    INNER JOIN BLOCOEXEC
        ON PASSOEXEC.ID = BLOCOEXEC.PASSOEXEC_ID
    INNER JOIN BLOCOOCORRENCIA
        ON BLOCOEXEC.OCORRENCIA_ID = BLOCOOCORRENCIA.ID
    LEFT JOIN BLOCO
        ON BLOCO.ID = BLOCOOCORRENCIA.BLOCO_ID
WHERE
    SESSAOEXEC.CANCELADA = 0
    AND MATRICULA.ID = :REGISTRATION_ID
    AND MATRICULA.PROJETO_ID = 132
    AND MATRICULA.PROGRAMA_ID = :PROGRAM_ID
    AND MATRICULA.ALUNO_ID = :STUDENT_ID
    AND BLOCO.ID IN (3839, 3843, 3847, 3240, 3241, 3242);