/*requires further processing to remove duplicated days*/
SELECT
    SESSAOEXEC.MOMENTOINICIO
FROM PESSOA
    INNER JOIN MATRICULA
        ON PESSOA.ID = MATRICULA.ALUNO_ID
    LEFT JOIN ALUNO
        ON PESSOA.ID = ALUNO.ID
    INNER JOIN SESSAOEXEC
        ON MATRICULA.ID = SESSAOEXEC.MATRICULA_ID
WHERE
    MATRICULA.PROJETO_ID = 132
    AND MATRICULA.ALUNO_ID = :STUDENT_ID
ORDER BY SESSAOEXEC.MOMENTOINICIO ASC;