SELECT
	TENTATIVA.ID AS FORWARD_TRIAL_ID,
    MATRICULA.ID AS MATRICULA_ID
FROM PESSOA
    INNER JOIN MATRICULA
        ON PESSOA.ID = MATRICULA.ALUNO_ID

    LEFT JOIN ALUNO
        ON PESSOA.ID = ALUNO.ID

    INNER JOIN SESSAOEXEC
        ON MATRICULA.ID = SESSAOEXEC.MATRICULA_ID

    INNER JOIN PASSOEXEC
        ON SESSAOEXEC.ID = PASSOEXEC.SESSAOEXEC_ID

    INNER JOIN PASSOOCORRENCIA AS PASSO_OCOR
        ON PASSOEXEC.OCORRENCIA_ID = PASSO_OCOR.ID

    LEFT JOIN PASSO
        ON PASSO.ID = PASSO_OCOR.PASSO_ID

    INNER JOIN BLOCOEXEC
        ON PASSOEXEC.ID = BLOCOEXEC.PASSOEXEC_ID

    INNER JOIN BLOCOOCORRENCIA
        ON BLOCOEXEC.OCORRENCIA_ID = BLOCOOCORRENCIA.ID

    LEFT JOIN BLOCO
        ON BLOCO.ID = BLOCOOCORRENCIA.BLOCO_ID

    INNER JOIN TENTATIVAEXEC
        ON BLOCOEXEC.ID = TENTATIVAEXEC.BLOCOEXEC_ID

    INNER JOIN TENTATIVAOCORRENCIA
        ON TENTATIVAEXEC.OCORRENCIA_ID = TENTATIVAOCORRENCIA.ID

    INNER JOIN TENTATIVA
        ON TENTATIVAOCORRENCIA.TENTATIVA_ID = TENTATIVA.ID

    INNER JOIN TENTATIVAINTERACAO
        ON TENTATIVAEXEC.ID = TENTATIVAINTERACAO.TENTATIVAEXEC_ID

WHERE
    SESSAOEXEC.CANCELADA = 0
    AND MATRICULA.PROJETO_ID = 132
    AND PASSO_OCOR.PROGRAMA_ID = :PROGRAM_ID
    AND MATRICULA.ALUNO_ID = :STUDENT_ID
    AND MATRICULA.ID = :REGISTRATION_ID
    AND TENTATIVA.ID IN (32216, 33048, 33049)
    ORDER BY MATRICULA.INICIO ASC