/* returns the oldest program's registration for a student*/
SELECT
    MATRICULA.ID

FROM MATRICULA

WHERE MATRICULA.ALUNO_ID in :STUDENT_IDS
    AND MATRICULA.PROJETO_ID = 132
    AND MATRICULA.PROGRAMA_ID = :PROGRAM_ID

ORDER BY MATRICULA.INICIO ASC