SELECT
    ESCOLA.ID,
    ESCOLA.NOME,
    ESCOLA.CIDADE,
    ESCOLA.UF
FROM PESSOA
    LEFT JOIN ALUNO ON ALUNO.ID = PESSOA.ID
    LEFT JOIN ESCOLA ON ESCOLA.ID = ALUNO.ESCOLA_ID
WHERE PESSOA.ID IN (
    SELECT MATRICULA.ALUNO_ID
    FROM MATRICULA
    WHERE MATRICULA.PROJETO_ID = 132
)
AND ALUNO.ID IN :STUDENT_IDS