/* By Leonardo Marques */

CREATE TABLE Resultado_AlfaTech_ALEPP_ID143
SELECT
       MATRICULA.`ALUNO_ID`,
       PESSOA.`NOMECOMPLETO`,
       PESSOA.SEXO,
       ALUNO.ESCOLARIDADEMAE,
       ALUNO.ESCOLARIDADEPAI,
       ALUNO.UF,
       ALUNO.CIDADE,
       PESSOA.`DATANASCIMENTO`,
       PASSO_OCOR.`PROGRAMA_ID`,
       PASSO_OCOR.`PASSO_ID` AS PASSO_ID,
       PASSO.`NOME` AS PASSO_NOME,
       BLOCO.`NOME` AS BLOCO_NOME,
       SESSAOEXEC.MOMENTOFIM AS DataExecucao,
       TentIntera.`TENTATIVAEXEC_ID`,
       TENTATIVA.NOME AS TENTATIVA_NOME,
       TENTATIVA.TIPOMODELO,
       EstModelo.NOME AS Modelo,
       EstComp1.NOME AS Comp1,
       EstComp1.DTYPE AS Comp1_Ttipo,
       EstComp2.NOME AS Comp2,
       EstComp2.DTYPE AS Comp2_Ttipo,
       EstComp3.NOME AS Comp3,
       EstComp3.DTYPE AS Comp3_Ttipo,
       TentMTSIntera.ESTIMULOSELECIONADO_ID AS EstSelecionado_ID,
       EstEscolhido.NOME AS Escolhido,
       TentIntera.`NROINTERACAO`,
       TentIntera.`RESULTADO`,
       TentIntera.`LATENCIA`,
       TentIntera.`DTYPE`

  FROM PESSOA
  INNER JOIN MATRICULA
     ON PESSOA.`ID` = MATRICULA.`ALUNO_ID`

   LEFT JOIN ALUNO
   ON  PESSOA.ID = ALUNO.ID

  INNER JOIN SESSAOEXEC
     ON MATRICULA.`ID` = SESSAOEXEC.`MATRICULA_ID`

  INNER JOIN PASSOEXEC
     ON SESSAOEXEC.`ID` = PASSOEXEC.`SESSAOEXEC_ID`

INNER JOIN PASSOOCORRENCIA AS PASSO_OCOR
     ON PASSOEXEC.`OCORRENCIA_ID`= PASSO_OCOR.`ID`

 LEFT JOIN PASSO
    ON PASSO.`ID` = PASSO_OCOR.`PASSO_ID`

  INNER JOIN BLOCOEXEC
     ON PASSOEXEC.`ID` = BLOCOEXEC.`PASSOEXEC_ID`

  INNER JOIN BLOCOOCORRENCIA AS BLC_OCOR
     ON BLC_OCOR.`ID` = BLOCOEXEC.`OCORRENCIA_ID`

 LEFT JOIN BLOCO
    ON BLOCO.`ID` = BLC_OCOR.`BLOCO_ID`

 INNER JOIN TENTATIVAEXEC
     ON BLOCOEXEC.`ID` = TENTATIVAEXEC.`BLOCOEXEC_ID`

INNER JOIN TENTATIVAOCORRENCIA
    ON TENTATIVAEXEC.`OCORRENCIA_ID` = TENTATIVAOCORRENCIA.`ID`

INNER JOIN TENTATIVA
    ON TENTATIVAOCORRENCIA.`TENTATIVA_ID` = TENTATIVA.`ID`

LEFT JOIN TENTATIVAMTS
    ON TENTATIVA.`ID` = TENTATIVAMTS.`ID`

LEFT JOIN ESTIMULO AS EstModelo
   ON TENTATIVA.`MODELOA_ID` = EstModelo.`ID`

LEFT JOIN ESTIMULO AS EstComp1
   ON TENTATIVAMTS.`ESTIMULOCOMPARACAO1A_ID` = EstComp1.`ID`

LEFT JOIN ESTIMULO AS EstComp2
   ON TENTATIVAMTS.`ESTIMULOCOMPARACAO2A_ID` = EstComp2.`ID`

LEFT JOIN ESTIMULO AS EstComp3
   ON TENTATIVAMTS.`ESTIMULOCOMPARACAO3A_ID` = EstComp3.`ID`


INNER JOIN TENTATIVAINTERACAO AS TentIntera
     ON TENTATIVAEXEC.`ID` = TentIntera.`TENTATIVAEXEC_ID`

LEFT JOIN TENTATIVAMTSINTERACAO AS TentMTSIntera
     ON TentIntera.`ID` = TentMTSIntera.`ID`

LEFT JOIN ESTIMULO AS EstEscolhido
   ON TentMTSIntera.`ESTIMULOSELECIONADO_ID` = EstEscolhido.`ID`

WHERE PASSO_OCOR.`PROGRAMA_ID` IN (143)
    AND MATRICULA.`ALUNO_ID` IN (6082)