/*
    Return registrations with time and student by target :PROGRAM_ID.
    Use to find student's ACOLEs ordered by time of ocurrence:
    370 with 1
    124 with 2
    9 with 3
    14 with FIM = NULL

 */
SELECT
    ID,
    INICIO,
    FIM,
    ALUNO_ID

FROM MATRICULA
WHERE MATRICULA.ALUNO_ID IN (
    SELECT MATRICULA.ALUNO_ID
    FROM MATRICULA
    WHERE MATRICULA.PROJETO_ID = 132
        AND MATRICULA.PROGRAMA_ID = :PROGRAM_ID
        AND MATRICULA.FIM IS NOT NULL
    GROUP BY MATRICULA.ALUNO_ID
    HAVING COUNT(MATRICULA.ALUNO_ID) = :COUNT
)
AND MATRICULA.PROJETO_ID = 132
AND MATRICULA.PROGRAMA_ID = :PROGRAM_ID
AND MATRICULA.FIM IS NOT NULL

ORDER BY
    MATRICULA.ALUNO_ID,
    MATRICULA.INICIO